name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022 # Must match Docker container
    env:
      IMAGE: ghcr.io/${{github.repository_owner}}/moodbar-test-deps-windows
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker build -t "${{env.IMAGE}}" windows/
      - name: Deploy
        if: ${{github.ref == 'refs/heads/dev'}}
        run: |
          echo "${{secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u $ --password-stdin
          docker push "${{env.IMAGE}}"
